[package]
name = "block-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.2.0", features = ["full"] }
colored = "2.1.0"
eyre = "0.6.12"
tokio = { version = "1.38.1", features = ["full"] }
